development:
  adapter: mysql2
  encoding: utf8
  database: test
  pool: 5
  username: root
  password: root
  reconnect: true

test:
  adapter: mysql2
  encoding: utf8
  database: test
  pool: 5
  username: root
  password: root
  reconnect: true

production:
  adapter: mysql2
  encoding: utf8
  database: test
  pool: 5
  username: root
  password: root
  reconnect: true
